CREATE ROLE :role PASSWORD :'password' LOGIN INHERIT CREATEDB NOCREATEROLE NOREPLICATION;
ALTER ROLE :role PASSWORD :'password' SUPERUSER;
GRANT :role to postgres;

CREATE DATABASE :database WITH OWNER = :role ENCODING UTF8 TEMPLATE template0;